### ISSUE TITLE
Add option to automatically copy from Windows clipboard

### ISSUE THREAD

**Issue by NightMean** [d2dyno1/ClipboardCanvas#8]
My idea is that whatever shows in the built in Windows clipboard should automatically show in Clipboard Canvas as well. 
This would make a perfect alternative for the built in one. 
Manual pasting is fine if you want to stay organized however saving everything is sometimes needed as well. 

Would it be possible to do it somehow?

**Comment by d2dyno1** [comment]
Hi! You can already do this in the latest version 🙂 

https://user-images.githubusercontent.com/53011783/177877228-c3ac10c0-548b-4310-8773-63ab6de144d2.mp4

**Comment by NightMean** [comment]
Oh, thank you for the heads-up! 
The autopaste setting made me think that this is somekind of Macro function which can automatically paste stuff from Collections to different applications (Seeing rules made me harden the guess)
